# PostgreSQL. Versions 8.2 and up are supported.
# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgresql
  encoding: unicode
  database: james_the_giant_development
  username: postgres
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: james_the_giant_test
  min_messages: warning

cucumber:
  <<: *test